R CMD BATCH 1.1.Soil_sample.R
R CMD BATCH 2.1.Select_grassland_component1.R
R CMD BATCH 2.2.Select_grassland_component2.R
R CMD BATCH 2.3.Join_Grassland_components.R
R CMD BATCH 3.1.Prepare_LF.R
R CMD BATCH 3.2.LF_process.R
R CMD BATCH 3.3.LF_alloca.R
R CMD BATCH 3.4.Select_LF_panel.R
R CMD BATCH 3.5.Select_LF_nonpanel.R 
R CMD BATCH 3.6.Compute_LF_weights.R
R CMD BATCH 4.1.Prepare_Copernicus.R
R CMD BATCH 4.2.Select_Copernicus_add.R
R CMD BATCH 4.3.Copernicus_Total.R
R CMD BATCH 4.4.Compute_Copernicus_weights.R
R CMD BATCH 5.Final_LUCAS27_sample.R
